server:
  port: 8084

spring:
  application:
    name: sale-product-api
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 50ms

rocketmq:
  name-server: 127.0.0.1:9876

merchandise:
  redis:
    ttl:
      base: 1800
      price: 600
      sku: 1800
      brand: 3600
      category: 3600
      image: 1800
      attribute: 1800
      description: 3600
